import { PublicNavbar } from '@/components/public/PublicNavbar'

const SECTIONS = [
  {
    title: 'Using the service',
    body:
      'AgencyOS is provided as a demo and product prototype. You may browse, test, and explore the available workflows, but you are responsible for how you use any output generated by the app.',
  },
  {
    title: 'Accounts and access',
    body:
      'If account features are enabled, you must provide accurate information and keep your access credentials secure. We may suspend access if activity appears abusive, fraudulent, or harmful.',
  },
  {
    title: 'Content and output',
    body:
      'Outputs generated by agents are intended to support your work. You should review them before using them in production, publishing them, or relying on them for decisions.',
  },
  {
    title: 'Service changes',
    body: 'We may change, pause, or remove features at any time as the product evolves.',
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <PublicNavbar />

      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-16 sm:py-20">
        <div className="mb-10">
          <p className="mb-4 text-xs font-medium uppercase tracking-widest text-slate-500">
            Legal
          </p>
          <h1 className="mb-4 text-balance text-4xl font-semibold text-foreground">
            Terms of service
          </h1>
          <p className="max-w-2xl leading-relaxed text-slate-600">
            These terms describe the basic rules for using the AgencyOS website and product demo.
          </p>
        </div>

        <div className="space-y-8">
          {SECTIONS.map((section) => (
            <section key={section.title} className="border-b border-slate-200 pb-8 last:border-0">
              <h2 className="mb-2 text-lg font-semibold text-foreground">{section.title}</h2>
              <p className="max-w-3xl text-sm leading-relaxed text-slate-600">
                {section.body}
              </p>
            </section>
          ))}
        </div>

        <div className="mt-12 rounded-lg border border-slate-200 bg-white p-6">
          <h2 className="mb-2 text-sm font-semibold text-foreground">Contact</h2>
          <p className="text-sm leading-relaxed text-slate-600">
            If you have questions about these terms, contact{' '}
            <a href="mailto:hello@agencyos.app" className="text-foreground hover:underline">
              hello@agencyos.app
            </a>
            .
          </p>
        </div>
      </main>
    </div>
  )
}
