import type { Agent, AgentOutput } from '@/lib/types'

interface RunInput {
  task: string
  context?: string
  desiredOutput?: string
  detailLevel?: string
}

export async function runMockAgent(agent: Agent, input: RunInput): Promise<AgentOutput> {
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 1800 + Math.random() * 1200))

  const task = input.task.trim()
  const agentName = agent.name
  const division = agent.division

  return {
    summary: `${agentName} analysis of: "${task.slice(0, 80)}${task.length > 80 ? '...' : ''}"`,
    mainResult: generateMainResult(agent, input),
    actionSteps: generateActionSteps(agent, input),
    risksNotes: generateRisksNotes(agent),
    suggestedNextStep: `Review the output and refine with a follow-up task. Consider using a ${division} specialist for the next phase.`,
    relatedAgents: getRelatedAgents(agent.slug),
  }
}

function generateMainResult(agent: Agent, input: RunInput): string {
  const task = input.task
  const detailNote = input.detailLevel === 'detailed' ? ' with full detail' : ''

  switch (agent.division) {
    case 'Engineering':
      return `Based on your task${detailNote}: "${task}"\n\n**Technical Assessment:**\nThis requires a structured approach with clear implementation phases. The key technical decisions involve architecture, maintainability, and performance trade-offs.\n\n**Recommended Approach:**\n1. Start with the core functionality before optimizing\n2. Use established patterns and avoid over-engineering\n3. Document decisions and trade-offs as you build\n4. Plan for testability from the start\n\n**Implementation Notes:**\nConsider the team's existing expertise and tooling. Prefer incremental delivery over large-batch changes. This analysis is generated by the mock provider — connect an AI provider for detailed, task-specific guidance.`

    case 'Design':
      return `Based on your task${detailNote}: "${task}"\n\n**Design Assessment:**\nThe core challenge is balancing clarity with functionality. Users need to understand the interface immediately without cognitive overhead.\n\n**Recommended Direction:**\n1. Prioritize visual hierarchy — most important actions first\n2. Use consistent spacing and type scales throughout\n3. Design for the 80% use case, not the edge cases\n4. Validate decisions with actual users before building\n\n**Design Notes:**\nMaintain a clear visual language throughout. Every element should have a purpose. This analysis is generated by the mock provider — connect an AI provider for detailed design guidance.`

    case 'Product':
      return `Based on your task${detailNote}: "${task}"\n\n**Product Assessment:**\nThe critical path to value is through clear scope definition and ruthless prioritization. Build for your core user first.\n\n**Recommended Approach:**\n1. Define the one metric that matters most\n2. Scope to the smallest useful version\n3. Identify and remove assumptions early\n4. Plan validation checkpoints before full build\n\n**Product Notes:**\nFocus beats breadth in early stage. Ship learning, not features. This analysis is generated by the mock provider — connect an AI provider for detailed product strategy.`

    case 'Sales':
      return `Based on your task${detailNote}: "${task}"\n\n**Sales Assessment:**\nEffective B2B sales requires clear ICP definition, specific pain-point messaging, and a repeatable outreach system.\n\n**Recommended Approach:**\n1. Define your ideal customer with firmographic and behavioral criteria\n2. Map the buying committee and their motivations\n3. Build messages around outcomes, not features\n4. Create sequences that educate before they sell\n\n**Sales Notes:**\nThe best sales is informed by product usage data. Track what converts. This analysis is generated by the mock provider — connect an AI provider for specific sales strategy.`

    case 'Security':
      return `Based on your task${detailNote}: "${task}"\n\n**Security Assessment:**\nThe primary risk areas involve authentication, authorization, and data protection. Defense in depth is the guiding principle.\n\n**Recommended Approach:**\n1. Enumerate all trust boundaries in the system\n2. Review each authentication and authorization path\n3. Check data handling for sensitive information exposure\n4. Test for common OWASP vulnerabilities\n\n**Security Notes:**\nSecurity is not a feature — it is a continuous practice. This analysis is generated by the mock provider — connect an AI provider for specific security analysis.`

    case 'Strategy':
      return `Based on your task${detailNote}: "${task}"\n\n**Strategic Assessment:**\nOperational excellence requires clear process ownership, documented procedures, and measurable outcomes.\n\n**Recommended Approach:**\n1. Map the current state before designing the future state\n2. Identify the highest-leverage bottlenecks first\n3. Design for the team that exists, not the ideal team\n4. Implement incrementally and measure improvement\n\n**Strategy Notes:**\nThe best operating system is the one your team actually follows. Start simple. This analysis is generated by the mock provider — connect an AI provider for detailed strategy guidance.`

    default:
      return `Analysis of: "${task}"\n\nThis is a demonstration output from the mock provider. Connect an OpenAI or Anthropic API key to receive real, task-specific AI analysis from the ${agent.name} agent.\n\nThe ${agent.name} agent specializes in ${agent.division} tasks with a focus on ${agent.shortDescription.toLowerCase()}.`
  }
}

function generateActionSteps(agent: Agent, input: RunInput): string[] {
  const baseSteps = [
    `Review the analysis above and identify which points are most relevant to your task`,
    `Prioritize the recommendations by impact and effort`,
    `Define clear acceptance criteria before starting implementation`,
    `Schedule a follow-up review after initial implementation`,
  ]

  switch (agent.division) {
    case 'Engineering':
      return [
        'Review the technical recommendations and validate against your constraints',
        'Break the implementation into small, testable increments',
        'Document key architectural decisions in your codebase',
        'Set up code review checkpoints before merging',
        'Test with real usage scenarios before shipping',
      ]
    case 'Design':
      return [
        'Sketch or wireframe the recommended layout direction',
        'Share with one real user for quick feedback',
        'Align with engineering on implementation constraints',
        'Create a component inventory before building',
        'Define success metrics for the design',
      ]
    case 'Product':
      return [
        'Document the MVP scope and get stakeholder sign-off',
        'Create a simple roadmap with phases and checkpoints',
        'Define the one key metric to track for success',
        'Schedule weekly review of progress against plan',
        'Plan the first user validation touchpoint',
      ]
    case 'Sales':
      return [
        'Finalize the ICP definition with your team',
        'Build your first prospect list using the ICP criteria',
        'Write and test the first outreach message',
        'Set up tracking for open rates and response rates',
        'Review and iterate based on first 20 outreach attempts',
      ]
    default:
      return baseSteps
  }
}

function generateRisksNotes(agent: Agent): string[] {
  const baseNotes = [
    'This output is from the mock provider. Connect an AI provider for specific, task-aware analysis.',
    'Validate recommendations against your specific context before implementing.',
  ]

  switch (agent.division) {
    case 'Engineering':
      return [
        'Risk: Over-engineering before validation — keep it simple until proven',
        'Risk: Technical debt accumulation — document decisions as you build',
        'Note: Connect an OpenAI/Anthropic key for real code-specific analysis',
      ]
    case 'Security':
      return [
        'Risk: Missing edge cases in authentication flows',
        'Risk: Insecure direct object references in API endpoints',
        'Note: Always validate security findings with a human security professional',
      ]
    case 'Product':
      return [
        'Risk: Scope creep before MVP — enforce strict prioritization',
        'Risk: Building without user validation — test early and often',
        'Note: Connect an AI provider for real product strategy analysis',
      ]
    default:
      return baseNotes
  }
}

function getRelatedAgents(currentSlug: string): string[] {
  const relatedMap: Record<string, string[]> = {
    'frontend-developer': ['backend-architect', 'ui-designer', 'code-reviewer'],
    'backend-architect': ['frontend-developer', 'security-reviewer', 'code-reviewer'],
    'ui-designer': ['ux-researcher', 'frontend-developer'],
    'ux-researcher': ['ui-designer', 'product-strategist'],
    'product-strategist': ['frontend-developer', 'ux-researcher', 'operations-strategist'],
    'sales-strategist': ['proposal-strategist', 'product-strategist'],
    'proposal-strategist': ['sales-strategist', 'technical-writer'],
    'security-reviewer': ['backend-architect', 'code-reviewer'],
    'code-reviewer': ['frontend-developer', 'backend-architect', 'security-reviewer'],
    'prompt-engineer': ['technical-writer', 'product-strategist'],
    'technical-writer': ['prompt-engineer', 'product-strategist'],
    'operations-strategist': ['product-strategist', 'sales-strategist'],
  }
  return relatedMap[currentSlug] || []
}
